apiVersion: "1.0.0"
kind: Deployment
metadata:
  name: simple-node
  labels:
    app: simple-node
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node
      version: "1.0.0"
  template:
    metadata:
      labels:
        app: simple-node
        version: "1.0.0"
    spec:
      containers:
        - name: simple-node
          image: abdoayman/simple-node:0.0.1
          ports:
            - containerPort: 80
